import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Parsa',
      email: 'parsa@admin.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Parsa',
      email: 'parsa@user.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Air Fly',
      slug: 'air-fly',
      category: 'Sport',
      image: '/images/sneaker.jpg',
      price: 700000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere et fuga error atque voluptates harum suscipit, ea culpa nostrum deserunt explicabo totam voluptas veniam consectetur sit veritatis quasi voluptatem aspernatur corrupti maiores vel voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
    {
      name: 'Air Max',
      slug: 'air-max',
      category: 'Men',
      image: '/images/shoe idk.png',
      price: 1600000,
      brand: 'Nike',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere et fuga error atque voluptates harum suscipit, ea culpa nostrum deserunt explicabo totam voluptas veniam consectetur sit veritatis quasi  voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
    {
      name: 'Air Jordan 1',
      slug: 'air-jordan-1',
      category: 'Men',
      image: '/images/idk nike.jpg',
      price: 4200000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet consectetur  voluptates harum suscipit, ea culpa nostrum deserunt explicabo totam voluptas veniam consectetur sit veritatis quasi voluptatem aspernatur corrupti maiores vel voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
    {
      name: 'Blazer Mid',
      slug: 'blazer-mid',
      category: 'Sport',
      image: '/images/blazer mid.jpg',
      price: 2500000,
      brand: 'Nike',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet adipisicing elit. Facere et fuga error atque voluptates harum suscipit, ea culpa nostrum deserunt explicabo totam voluptas veniam consectetur sit veritatis quasi voluptatem aspernatur corrupti maiores vel voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
    {
      name: 'Jordan 1 Mid',
      slug: 'jordan-1-mid',
      category: 'Sport',
      image: '/images/Jordan red.jpg',
      price: 800000,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet consectetur vel voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
    {
      name: 'Air Force 1',
      slug: 'air-force-1',
      category: 'Women',
      image: '/images/some good shoe.png',
      price: 1200000,
      brand: 'Nike',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere et fuga error atque voluptates harum suscipit, ea culpa nostrum deserunt explicabo totam voluptas veniam consectetur sit veritatis quasi voluptatem aspernatur corrupti maiores vel voluptatum dolorem nemo? Distinctio laudantium tempora laboriosam. Soluta in, minus id distinctio molestiae quasi voluptas amet repellat, natus iste debitis suscipit saepe excepturi doloremque explicabo iusto asperiores velit expedita dignissimos eos necessitatibus sint eligendi! Dolorum nulla sapiente quasi dolore laudantium quos! Repellendus, accusamus? Perferendis eaque nostrum tenetur?',
    },
  ],
};

export default data;
